### ISSUE TITLE
方針転換

### ISSUE THREAD

**Issue by mashiike** [mashiike/stefunny#166]
現状のStefunnyだと、いまいち利点がないと感じています。
結局Terraformで管理すれば良いじゃないか？　という
JsonnetやGo Templateで書きやすくはなっているものの、ASLの複雑性がそのまま残ってしまっているのでどうしたものかと考えています。

Workflowでのリトライ制御というのが結構肝だなと思っていて、Github Actionsのように簡単に書ければいいんじゃないかなと思い始めています。
```yaml
RequiredVersion: >=0.6.0
Trigger: 
  Scheduler:
    - Expression: rate(1 day)

Branches:
   ECSRunTask:
     Defaults:
       Retry: 5
       FaildReporter: arn:aws:sns:ap-northeast-1:000000000000:MyTopic
     Steps:
       - Name: hello
         Uses: stefunny/ecs-run-task
         With: 
            TaskDefinitionARN: arn:aws:ecs:ap-northeast-1:000000000000:task-definition/hello
            Subnets:
               - subnet-00a78dcxxxxxxxxxx
             SecurityGroups:
               - sg-0600d2cxxxxxxxxxx
       - Name: pass
         Type: Pass
         Parameters:
            "ID.$": "States.StringSplit(States.UUID(), '-')"
         "ResultPath": "$.hoge"
   ```
   例えば、このような感じで書くことで、各ステップで５回のリトライをして
   全部失敗したらSNSTopicに送信するというような挙動をするように設定できたら、すごく便利だと思っています。
Usesの部分は、Jsonnetかなにかでテンプレートを展開するようなイメージです。
